name: Auto Versioning

on:
  push:
    branches: [ main ]

jobs:
  # 1. Adicionamos a permissão de escrita
  permissions:
    contents: write

  auto-version:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout do código
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 2. Configurar Git
      run: |
        git config --global user.name 'CI Bot'
        git config --global user.email 'ci-bot@github.com'

    # 3. Incrementar Versão
    - name: 3. Incrementar Versão
      # Damos um "id" a este passo para referenciá-lo depois
      id: increment_version
      run: |
        LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
        if [[ "$LAST_COMMIT_MSG" == "CI: Incrementa versão para"* ]]; then
          echo "Versão já incrementada por CI Bot. Saindo."
          exit 0
        fi
        
        CURRENT_VERSION=$(cat version.txt)
        BASE_VERSION=$(echo $CURRENT_VERSION | cut -d'v' -f2)
        MAJOR=$(echo $BASE_VERSION | cut -d'.' -f1)
        MINOR=$(echo $BASE_VERSION | cut -d'.' -f2)
        PATCH=$(echo $BASE_VERSION | cut -d'.' -f3)
        
        NEW_PATCH=$((PATCH + 1))
        
        NEW_VERSION="v${MAJOR}.${MINOR}.${NEW_PATCH}"
        echo "Versão atual: $CURRENT_VERSION -> Nova versão: $NEW_VERSION"
        
        echo $NEW_VERSION > version.txt
        
        # 2. Esta linha "exporta" a variável para os próximos passos
        echo "::set-output name=NEW_VERSION_STEP::$NEW_VERSION"

    # 4. Commitar e Fazer Push da Nova Versão
    - name: 4. Commitar e Fazer Push da Nova Versão
      run: |
        # 3. Usamos a variável exportada do passo anterior
        NEW_VERSION_FROM_STEP="${{ steps.increment_version.outputs.NEW_VERSION_STEP }}"
        
        # Verificamos se a variável não está vazia (caso o passo 3 tenha saído)
        if [ -z "$NEW_VERSION_FROM_STEP" ]; then
          echo "Nenhuma nova versão para commitar. Saindo."
          exit 0
        fi
        
        git add version.txt
        git commit -m "CI: Incrementa versão para $NEW_VERSION_FROM_STEP"
        git push origin main
